Add missing nbs fields to enable use of StreamReactor in the NUC side
NUbots/NUcontroller pull request #10
Opened 2024-04-12 05:19 UTC by JohanneMontano

2024-04-26 06:50 UTC, Claegtun requested changes
Overall, this needs to be tested on the robot first, ideally with KeyboardWalk, etc. such that we know that no functionality has accidently been lost and that no new bugs spring up.

Therefore, this review may only be ephemeral since more changes may be made henceforth.

Lastly, this should be merged at the same time as the corresponding HardwareIO branch.

2024-05-07 05:41 UTC, ysims approved these changes

2024-05-09 22:59 UTC, Claegtun commented on NUSense/Core/Src/usb/PacketHandler.hpp
> +                    pb_length = static_cast<uint32_t>(rx_buffer.data[(rx_buffer.front + 3) % RX_BUF_SIZE] << 0)
Actually, never mind; it is fine as it is.

2024-05-10 03:06 UTC, Claegtun requested changes

2024-05-10 03:06 UTC, Claegtun commented on NUSense/Core/Src/test_hw.hpp
>  }  // namespace test_hw
```suggestion
}  // namespace test_hw

```
Just quickly change this for me.

2024-05-10 06:48 UTC, Claegtun approved these changes
Seems good.

2024-05-10 06:50 UTC, Claegtun commented
However, we may want to wait until the other PR is ready to merge as well.

2024-05-13 02:26 UTC, ysims commented
This may as well be merged, none of the NUSense stuff on here works with main on NUbots/NUbots and the branch on that side is stream reactor now anyway.

2024-05-14 00:34 UTC, merged