Integrate all the different components such that the basic functionality is working.
NUbots/NUcontroller pull request #11
Opened 2024-04-15 00:33 UTC by Claegtun

Integrates all of the diferent sections of the code that have been worked on so far into one whole system. 

Furthermore, investigates and fixes any major bugs and introduces further code needed such that the basic functionality (e.g. ScriptTuner, KeyboardWalk, etc.) is working on a robot. This is not withstanding any hopefully small bugs and improvements that may come up later. 

Such changes are:
- converting gyroscope data to radians,
- removing some redundant legacy code for offsets and directions,
- adding a cooldown between the two write-instrucions whenever the torque was switched on*,
- adding the correct timespan from the NUC to the servo-state,
- inverting the axes for both the accelerometer and the gyroscope,
- setting the profile-velocities to one second on start-up,
- and fixing some bugs with the USB packt-handler and the torque.

This should hopefully mark the milestone in the overall development for NUSense. The next phase should be impovement and bug-monitoring.

* For posterity: this was a bug where the servo would move erratically, mainly quickly, whenever it was given a goal-position shortly after the torque was switched on from off. This was as if the servo was ignoring the profile-velocity. Delaying the two write-instructions for each servo seemed to fix this, but the cause is still not clear. No Robotis documentation mentions anything about this.

2024-04-15 03:12 UTC, ysims commented on NUsenseCpp/Core/Src/usb/PacketHandler.hpp
> +                //rx_flag = 0;
commented code? whats happening with this flag

2024-04-15 04:35 UTC, Claegtun commented on NUsenseCpp/Core/Src/usb/PacketHandler.hpp
> +                //rx_flag = 0;
We are no longer using it for checking the state of the rx-buffer. So, we can remove that commented line.

2024-04-15 04:36 UTC, Claegtun commented on NUsenseCpp/Core/Src/usb/PacketHandler.hpp
> +                //rx_flag = 0;
... or maybe even variable itself.

2024-04-15 23:12 UTC, JohanneMontano commented
Will leave a review asap, probs by the end of today

2024-04-16 03:09 UTC, JohanneMontano requested changes

2024-04-16 03:09 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/loop.cpp
> +                auto new_target = &(new_targets->targets[i]);
```suggestion
                message_actuation_ServoTarget new_target = &(new_targets->targets[i]);
```

Better to be more explicit with the type when it is not known right away, e.g.,

`auto sensors = std::make_unique<Sensors>();` is fine since the type sensors is there. Just for the sake of readability

2024-04-16 03:09 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/send_nusense_data.cpp
> +        nusense_msg.imu.gyro.z   = -converted_data.gyroscope.z;
It might be useful to leave a comment describing why y and z is negative

2024-04-16 03:09 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/startup.cpp
> +                // with the returned status.
```suggestion
                /* Send the write-instruction again if there is something wrong 
                * with the returned status.
                /
```

2024-04-16 03:09 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/usb/PacketHandler.hpp
> +                //rx_flag = 0;
This can be deleted, together with the corresponding declarations in `usbd_cdc_if.h/c `because rx_buffer.size is our "new" and "implicit" rx_flag i.e., if the size is not 0 then we must have received something since the callback has been called

2024-04-16 03:09 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/usb/PacketHandler.hpp
> +                else {
Can we remove the bit that had the redundant checking implemented? Im talking about the thing that caused the bug in the nuc side as ideally we'd like both packet handlers to be identical in both devices, at least until StreamReactor

2024-04-16 04:24 UTC, Claegtun commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/startup.cpp
> +                // with the returned status.
From what I have seen elsewhere on the NUbots repository, it seems that `//` is the convention for multiline explanatory comments.

2024-04-16 04:32 UTC, Claegtun commented on NUsenseCpp/Core/Src/usb/PacketHandler.hpp
> +                else {
Done.

2024-04-16 04:32 UTC, Claegtun commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/send_nusense_data.cpp
> +        nusense_msg.imu.gyro.z   = -converted_data.gyroscope.z;
Done.

2024-04-16 04:32 UTC, Claegtun commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/loop.cpp
> +                auto new_target = &(new_targets->targets[i]);
Done, although it has to be `message_actuation_ServoTarget*`.

2024-04-16 04:32 UTC, Claegtun commented on NUsenseCpp/Core/Src/usb/PacketHandler.hpp
> +                //rx_flag = 0;
Done.

2024-04-16 04:32 UTC, Claegtun commented on NUsenseCpp/Core/Src/usb/PacketHandler.hpp
> +                //rx_flag = 0;
Done.

2024-04-16 04:42 UTC, ysims commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/startup.cpp
> +                // with the returned status.
`//` defs

2024-04-16 04:42 UTC, ysims approved these changes

2024-04-16 05:06 UTC, JohanneMontano approved these changes

2024-04-16 05:14 UTC, merged