Rework packet handling with a Chain class + ID discovery
NUbots/NUcontroller pull request #14
Opened 2024-05-04 07:36 UTC by dex-k

This is still a WIP but the PR implements:
- A `Chain` class which basically abstracts a collection of dynamixel devices on a shared port
- A `ChainManager` class which is basically a collection of chains, and handles higher level tasks like
  - triggering ID discovery on chains
- Refactoring to use the new `Chain` and `ChainManager` classes
- Some random fixes and stuff I felt like doing along the way (these probably should have been separate PRs, maybe I'll still split them up if I can be bothered):
  - Clean up some of the code which handles the IMU
  - Adds a Debug config within CubeIDE which disables all optimisations to allow for variable inspections, etc. and updates the `.gitignore` for this.

TODO:
- Finish implementing ID discovery and make it all fully functional
- Error handling for duplicate IDs or missing IDs
- General bux fixes are more thorough testing
- Probably more stuff, I just wanted to get a draft PR up for now.

2024-05-04 12:20 UTC, ysims commented on NUSense/Core/Src/dynamixel/PacketHandler.hpp
> +                // We recieved at least one byte, so restart the timer and decode it
```suggestion
                // We received at least one byte, so restart the timer and decode it
```

2024-05-04 12:21 UTC, ysims commented on NUSense/Core/Src/dynamixel/PacketHandler.hpp
> +                // Check the recieved status packet has the expected length to ensure it isn't an error packet.
```suggestion
                // Check the received status packet has the expected length to ensure it isn't an error packet.
```

2024-05-04 12:28 UTC, ysims commented on NUSense/Core/Src/platform/NUSense/ChainManager.hpp
> +namespace platform::NUSense {
do we need the extra platform namespace, everything is nusense anyway

2024-05-05 01:51 UTC, dex-k commented on NUSense/Core/Src/platform/NUSense/ChainManager.hpp
> +namespace platform::NUSense {
Yeah I thought the same. I also think it's useless, I just figured it was there for a reason lol

2024-05-07 23:50 UTC, Claegtun requested changes
Some very small nitpicks on commenting, etc., but we should address the number of chains.

2024-05-07 23:50 UTC, Claegtun commented on NUSense/Core/Src/dynamixel/Chain.hpp
> +                    default: break;
Did you also want to add `case PacketHandler::Result::TIMEOUT` for completeness?

2024-05-07 23:50 UTC, Claegtun commented on NUSense/Core/Src/dynamixel/Chain.hpp
> +        /// @retval A reference to the vector of devices in the chain.
```suggestion
        /// @return A reference to the vector of devices in the chain.
```
Small nitpick: I am no expert on Doxygen, but I thought that `@retval` was for discrete named values like an enumeration or a boolean, and `@return` was for arbitrary values or references. See [this](https://sourceforge.net/p/doxygen/mailman/message/11651182/) and [this](https://micro-os-plus.github.io/develop/doxygen-style-guide/).

2024-05-07 23:50 UTC, Claegtun commented on NUSense/Core/Src/dynamixel/Chain.hpp
> +        bool contains(platform::NUSense::NUgus::ID id) const {
Small nitpick: We may want to get into the habit of adding `@param` as well.

2024-05-07 23:50 UTC, Claegtun commented on NUSense/Core/Src/dynamixel/Chain.hpp
> +        PacketHandler& get_packet_handler() {
Small nitpick: Should there be a `const` over the braces like `get_port`?

2024-05-07 23:50 UTC, Claegtun commented on NUSense/Core/Src/dynamixel/Chain.hpp
> +            index = (index + 1) % devices.size();
Do we want to move along the chain of devices or rather the chain of servos? I guess that this is a debate about how we would use NUfsr, i.e. whether we want to poll NUfsr at the same rate as the servos, etc. Maybe for future-proofing, we could have `next_device` and `next_servo`. Just a thought.

2024-05-07 23:50 UTC, Claegtun commented on NUSense/Core/Src/dynamixel/PacketHandler.hpp
> +        PacketHandler(uart::Port& port) : port(port), packetiser(), result(NONE), timeout_timer(){}
I wonder why the formatting has changed.

2024-05-07 23:50 UTC, Claegtun commented on NUSense/Core/Src/platform/NUSense/ChainManager.hpp
> +namespace platform::NUSense {
ServoID is in platform but not in NUSense, no?

2024-05-07 23:50 UTC, Claegtun commented on NUSense/Core/Src/platform/NUSense/ChainManager.hpp
> +        /// @param ports The ports to use for each chain.
Does this need to be updated since it is an array of  `Chain`s?

2024-05-08 00:01 UTC, Claegtun requested changes
This was meant to be part of the review above.

2024-05-08 00:01 UTC, Claegtun commented on NUSense/Core/Src/platform/NUSense/NUSenseIO.hpp
> +            , imu() {}
~For some reason, GitHub forgot to add this comment which happened to be the most important; so, I have to type this all out again.~

We should ideally, at least at the start, have six chains for all six ports. By only having these five chains here, we limit ourselves to only use the first five headers on the board itself. The goal of this PR was to make NUSense as plug-and-play as it can be with the servos. Ideally, we don't want team-members to have to remember the ports only into which they can plug or forget and accidently plug into the sixth header and spend ten minutes trying to find out why it doesn't work.

Also, we would like to keep the door open to experiement with other chain-arrangements that may have six chains. Overall, we would like NUSense to dynamically adapt to any chain-arrangement (within reason).

However, I do understand that this may often mean that we will always have an empty chain in the array of chains and that this somewhat ruins the simplicity of just looping through a simple array. Maybe we could have a check for whether the chain is empty in the main loop or maybe even a vector instead of an array.

2024-05-08 08:11 UTC, dex-k commented on NUSense/Core/Src/dynamixel/Chain.hpp
> +            index = (index + 1) % devices.size();
Good point, some difficulties around having separate next()'s in regards to the weighting and the device and servo indexes going out of sync.

I don't really see the need to be polling devices at different rates at this point, especially if we're only returning data to the NUC at a constant rate. The only use case I see currently is if the FSRs would need special filtering and hence a higher polling rate, but if the FSRs are going to be a dynamixel device and have their own processing, I don't see why the filtering shouldn't be done by the FSR, to then return an already filtered value when polled by the NUsense.

Either way, I'm leaning toward noting down the idea and pushing the added functionality to a future FSR related PR.

2024-05-08 08:12 UTC, dex-k commented on NUSense/Core/Src/dynamixel/PacketHandler.hpp
> +        PacketHandler(uart::Port& port) : port(port), packetiser(), result(NONE), timeout_timer(){}
I removed the empty newly between the function braces for consistency with the other constructors! and the formatter decided that meant it should all go on one line.

2024-05-08 08:17 UTC, dex-k commented on NUSense/Core/Src/platform/NUSense/NUSenseIO.hpp
> +            , imu() {}
Yeah I was iffy about adding in NUM_CHAINS. I pretty much agree with everything you said, I'm happy to entirely remove it to allow for flexibility (and because ideally we find an arrangement which most evenly spreads the load).

Might be worth benchmarking how much an empty chain even affects it, tbh I doubt it does much at all.

2024-05-08 22:18 UTC, TrentHouliston reviewed
I'll review more later but I had these comments sitting in my review history so I should probably push them up

2024-05-08 22:42 UTC, Claegtun commented on NUSense/Core/Src/dynamixel/Chain.hpp
> +        PacketHandler& get_packet_handler() {
Never mind. I don't think so since it is a reference.

2024-05-08 23:08 UTC, TrentHouliston commented on NUSense/Core/Src/dynamixel/Chain.hpp
> +            index = (index + 1) % devices.size();
If you wanted to adjust the polling rates etc down the line I would suggest that you keep each device in your list, but have a separate "request queue" that you fill up with the actual request order, then you can do things like `servo_a, fsr, servo_b, fsr` or any other combination doubling up as needed. But for now I agree, just poll all the devices I think that so long as the rates are high enough the increase in code complexity isn't really worth the potential benefits at this stage

2024-05-08 23:24 UTC, TrentHouliston commented on NUSense/Core/Src/dynamixel/Chain.hpp
> +#endif  // DYNAMIXEL_CHAIN_HPP
Should fix up your ide so it puts newlines at the ends of files so you don't get github putting these at the end

2024-05-08 23:24 UTC, TrentHouliston commented on NUSense/Core/Src/imu.cpp
> +void platform::NUSense::IMU::init() {
I know you're not really editing this file in this PR, but if you put a namespace scope in your cpp file then you don't need all the extra stuff on the front of each function here

2024-05-08 23:24 UTC, TrentHouliston commented on NUSense/Core/Src/imu.cpp
> +void platform::NUSense::IMU::writeReg(Address addr, uint8_t data) {
when you get to this, if the convention for functions is `snake_case` this does not match

2024-05-08 23:24 UTC, TrentHouliston commented on NUSense/Core/Src/platform/NUSense/NUgus.hpp
Longer term for NUsense you probably want to make it not care about what each servo is, that's a job for the NUC. Just when you discover a new "device" send a query to its model number and then decide what kind of parser you need based on that. so if it's an MX106 you set up the right parser for it, and if it's a FSR you set up the model for that

2024-05-08 23:24 UTC, TrentHouliston commented on NUSense/Core/Src/platform/NUSense/NUSenseIO/startup.cpp
>                          {uint16_t(dynamixel::DynamixelServo::Address::FEEDFORWARD_1ST_GAIN_L),
In c++ you should avoid c style casts (I know you didn't edit this code but I thought I'd flag it)

Also this is mixed casts, you're doing c style for the first two then functional for the third.

2024-05-08 23:24 UTC, TrentHouliston commented on NUSense/Core/Src/dynamixel/Chain.hpp
> +        const uint8_t get_index() const {
first const does nothing

2024-05-09 00:31 UTC, dex-k commented on NUSense/Core/Src/dynamixel/Chain.hpp
> +                    default: break;
I'm not sure, we will never get a `Result::TIMEOUT` here because the broadcast ping doesnt start the `PacketHandler::timeout_timer` (i.e. we only `ready()` it, we don't `begin()` it), instead we use the `Chain::utility_timer` (same as is used for write instruction 1ms cooldown). The reasons for this are twofold: `PacketHandler::timeout_timer` is a microsecond timer and can't handle 759ms without overflow, and the broadcast ping timeout doesn't care about single-packet timeouts (effectively, these are expected, as _most_ IDs will be missing in a chain), and rather the timeout is relevant to the `Chain` as a whole.

Having now entirely over explaine it, I think it's probably worth adding for completeness to explain exactly this lol.

2024-05-09 00:39 UTC, dex-k commented on NUSense/Core/Src/imu.cpp
> +void platform::NUSense::IMU::init() {
True, never thought of that. Is it better convention to `namespace platform::NUSense` or `namespace platform::NUSense::IMU`? Obiously the latter allows for less extra stuff but it also feels like keeping the `IMU` is useful especially to clarify return types like `IMU::ConvertedData`.

2024-05-09 00:41 UTC, dex-k commented on NUSense/Core/Src/platform/NUSense/NUSenseIO.hpp
> +            , imu() {}
Keeping the `NUM_CHAINS` variable for readability and potential future stuff (a port breaks or something..?), but setting `NUM_CHAINS = NUM_PORTS`.

2024-05-13 03:37 UTC, TrentHouliston commented on NUSense/Core/Src/imu.cpp
> +void platform::NUSense::IMU::init() {
You can't do it for the class itself, you can only namespace into namespaces. IMU in this case is the class

2024-05-13 04:53 UTC, dex-k commented on NUSense/Core/Inc/imu.h
> +        };
Leaving this for later as we're going to re-vamp IMU stuff shortly anyway to use DMA, so actual changes of substance to the IMU class belong to that PR.

2024-05-13 04:56 UTC, dex-k commented on NUSense/Core/Src/platform/NUSense/NUgus.hpp
Yep, agreed. There's a TODO for model number handling, as the Ping status return actually includes model number and firmware version, which makes this simple to implement (additional parser implementation notwithstanding). Pushing this to the future FSR PR though as for now we don't have to handle any non servo devices.

2024-05-13 23:07 UTC, JohanneMontano submitted a review, later dismissed
I think it'd be best if you waited for stream reactor to be approved and merged. You're touching files that concern the comms eg., nanopb files and PacketHandlers which stream reactor relies on.

2024-05-14 01:55 UTC, JohanneMontano approved these changes
lgtm

2024-05-14 02:29 UTC, Claegtun approved these changes
Seems good.

2024-05-14 02:29 UTC, merged