Fix broken OpenCR buzzer
NUbots/NUcontroller pull request #20
Opened 2024-07-03 10:14 UTC by dex-k

This PR:
- Fixes an issue where the buzzer does not sound when it should.
- Adds buzzer test functionality to the debug menu.
- Increments firmware version to `5` to reflect these changes.

The buzzer was broken as battery voltage monitoring called `noTone()` in the off state, which overrides any previous `tone()` calls which hadn't finished yet. The `noTone()` was redundant anyway because all `tone()`'s called within the voltage monitoring function had a duration set anyway.

Draft because it's late and I haven't tested it in a real robot, only with debug mode tests.

2024-07-03 23:39 UTC, JohanneMontano requested changes
Just a few notes, mostly lgtm

2024-07-03 23:39 UTC, JohanneMontano commented on OpenCR/src/debug/dxl_debug.cpp
> +        ;
```suggestion
    while (!DEBUG_SERIAL.available()) {}
```

2024-07-03 23:39 UTC, JohanneMontano commented on OpenCR/src/hardware/dxl_hw_op3.cpp
>          // /// Serial.println(vol_value);
```suggestion
```

2024-07-03 23:39 UTC, JohanneMontano commented on OpenCR/src/hardware/dxl_hw_op3.cpp
>                  // }
```suggestion
```

This looks like it can be useful but if not we can get away with removing it

2024-07-04 05:22 UTC, JohanneMontano commented on OpenCR/src/protocol/dxl_node_op3.cpp
> +#define RANGE_CHECK(addr, data, x) dxl_node_check_range(addr, (uint32_t) & (x), sizeof(data), sizeof(x))
I guess this is why some people hate macros lol

2024-07-04 05:22 UTC, JohanneMontano commented on OpenCR/src/protocol/dxl_node_op3.cpp
> +#define RANGE_CHECK(addr, data, x) dxl_node_check_range(addr, (uint32_t) & (x), sizeof(data), sizeof(x))
that said, it might be worth making this thing as a real function so we can debug it properly next time

2024-07-04 05:30 UTC, JohanneMontano commented on OpenCR/src/protocol/dxl_node_op3.cpp
> +        return FALSE;
why do they have macros for booleans as well? Can we just replace this with the c++ ones

2024-07-04 07:30 UTC, dex-k commented on OpenCR/src/debug/dxl_debug.cpp
> +        ;
The auto-formatting is equally bad with braces added. I prefer no braces stylistically, is there a NUbots convention?

2024-07-04 07:32 UTC, dex-k commented on OpenCR/src/protocol/dxl_node_op3.cpp
> +#define RANGE_CHECK(addr, data, x) dxl_node_check_range(addr, (uint32_t) & (x), sizeof(data), sizeof(x))
Hopefully there won't be a next time

2024-07-04 07:35 UTC, dex-k commented on OpenCR/src/protocol/dxl_node_op3.cpp
> +        return FALSE;
I don't think it's worth changing stuff like this, it works as is the code is just in a different (dumb) convention. There's an endless list of cleanup we could do to the ROBOTIS code if we wanted to, but it's just as easy to just work with what we've got. Within a few months OpenCR will just be a backup.

2024-07-05 01:43 UTC, JohanneMontano commented on OpenCR/src/debug/dxl_debug.cpp
> +        ;
We can sort this stuff in a new pr thats focused on formatting and conventions

2024-07-05 02:36 UTC, dex-k commented on OpenCR/src/protocol/dxl_node_op3.cpp
> +#define RANGE_CHECK(addr, data, x) dxl_node_check_range(addr, (uint32_t) & (x), sizeof(data), sizeof(x))
Replaced the macro and changed the function. Code looks uglier but hopefully helps someone debugging in the future.

2024-07-05 02:43 UTC, JohanneMontano approved these changes

2024-07-05 02:43 UTC, merged