Initialise NUSense <-> NUC communication protocol
NUbots/NUcontroller pull request #3
Opened 2023-09-29 06:33 UTC by JohanneMontano

Written the test, next TODO is to decode the packets that are coming from the NUC, encode status returns in NUSense and send to NUC then decoding in the NUC side

2023-09-29 06:45 UTC, TrentHouliston commented
Don't commit generated code, generate it on the fly instead

2023-09-29 13:55 UTC, jpptm commented
@TrentHouliston that would probably involve the whole nanopb repo/build to be included somewhere in the tools section of NUbots/NUbots then use subprocess to run the generator script then probs use firmware installer to write the files to NUsense. Is this how you expect this to go? The pb.cc and pb.h counterparts of a normal pb message have to be in the NUC for the code to compile in that side if we're going with this.

2023-12-03 03:10 UTC, jpptm requested changes
Some TODOs need to be done for it to work iteratively. This will currently only work if the buffer is not exceeded.

2023-12-03 03:10 UTC, jpptm commented on NUsenseCpp/USB_DEVICE/App/usbd_cdc_if.c
> +	rx_buf_len = rx_buf_len + rx_len;
```suggestion
	rx_buf_len = (rx_buf_len + rx_len) % RX_BUF_SIZE;
```

Make sure to wrap around so we dont get a segfault later. This variable just notes the element after the last byte in the buffer so this should be fine

2023-12-03 03:19 UTC, jpptm submitted a review, later dismissed

2023-12-03 03:30 UTC, jpptm commented on NUsenseCpp/Core/Src/test_hw.hpp
> +			}
Splitting it into 2 memcpy calls after checking if there is enough space in the buffer apparently does not seem too bad as it sounds

2023-12-23 09:17 UTC, jpptm commented on NUsenseCpp/USB_DEVICE/App/usbd_cdc_if.c
> +	rx_buf_len = rx_buf_len + rx_len;
👍

2023-12-23 09:17 UTC, jpptm commented on NUsenseCpp/USB_DEVICE/App/usbd_cdc_if.c
> +	memcpy(&rx_buf[rx_buf_len], &Buf[0], rx_len);
👍

2023-12-23 09:21 UTC, jpptm commented on NUsenseCpp/Core/Src/test_hw.hpp
> +			}
👍

2023-12-23 09:22 UTC, jpptm commented
TODO add callback function to extract ServoTarget field from ServoTargets

2024-03-01 00:05 UTC, JohanneMontano commented
Might have to bring some of the necessary .cproject files, etc., it is very inconvenient to not be able to build after initial setup.

2024-03-23 22:45 UTC, Claegtun commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/transmit.cpp
Maybe rename this file to something less ambigiuous like 'send_over_usb.cpp' or maybe even better the name of the function itself 'send_servo_states.cpp'.

2024-03-23 22:45 UTC, Claegtun commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO.hpp
> +        NU_IMU_converted_data converted_data;
The IMU stuff is fine for now as a placeholder, but when it gets merged with `imu-mvp`, it will have to change, e.g. the C-like namespacing, 'NU_IMU_'.

2024-03-23 22:45 UTC, Claegtun commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/transmit.cpp
Also, watch this space. We need to test how quick this code is, maybe after this gets merged, preferrably before it does. Just wrap `send_servo_states` with SET_SIGNAL_x and RESET_SIGNAL_x. (you may also have to disable other signals.)

2024-03-25 04:16 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/transmit.cpp
I may have to get guidance from you to set salea up properly

2024-03-25 04:21 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/transmit.cpp
oh so those functions just control the state of the pins within JP501. Should be able to figure it out :+1:

2024-03-25 04:50 UTC, Claegtun commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/transmit.cpp
To be honest, you can just remove all references to (RE)SET_SIGNAL_x, except for the declarations of course, and just use (RE)SET_SIGNAL_1. We should get in the habit of not committing them within code. But I will show you this week.

2024-03-28 01:14 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO.hpp
> +        NU_IMU_converted_data converted_data;
Will address once we solve the conflicts in the imu mvp pr

2024-03-28 01:24 UTC, Claegtun approved these changes
Seems good to me.

2024-03-28 01:25 UTC, merged