Add an IMU class with easy reading and writing
NUbots/NUcontroller pull request #6
Opened 2024-03-12 00:49 UTC by dex-k

Doesn't yet include DMA as it won't make a massive difference and there's more important things atm.

Includes tests in `test_hw.hpp`, and instructions at the top of `imu.h`.

Still needs to be tested once more since I've refactored it (which shouldn't make a difference, but just in case), but I can't do that atm.

2024-03-12 02:00 UTC, dex-k reviewed
Tested and working

2024-03-15 00:56 UTC, JohanneMontano requested changes
Initial review. Deleting the .mxproject (or any of the .cproject files,  etc) caused a lot of problems when trying to get cube to compile the binaries. What was the reason for deleting these files? I'd rather have them in the repo so when I git clone anytime for any reason I can just start developing and building stuff right away

2024-03-15 00:56 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/imu.cpp
> +using namespace NUsense;
```suggestion
```

2024-03-15 00:56 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/imu.cpp
>      HAL_Delay(1);
why is this here?

2024-03-15 00:56 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/imu.cpp
> +                                 // FIFO_EN_ACCEL_FIFO_EN
Commented code. Probably good to explain what these arguments do if we are to commit this to main

2024-03-15 00:56 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/imu.cpp
> +};
Add newline here so git doesnt cry about it

2024-03-15 00:56 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/main.cpp
>  }
We should probably agree on what formatter to use so its consistent in the whole code base.

2024-03-15 00:56 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/test_hw.hpp
> +// #include "uart/RS485.h"
Address commented code

2024-03-15 00:56 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/test_hw.hpp
> +    #define SRC_TEST_HW_HPP_
Put the macroguard before the includes so the formatter doesnt indent it like this

2024-03-15 00:56 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/test_hw.hpp
> +            link.transmit_poll((uint8_t*) &c, 1, HAL_MAX_DELAY);
Address commented code

2024-03-15 00:56 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/test_hw.hpp
> +            link.transmit_poll((uint8_t*) &c, 1, HAL_MAX_DELAY);
Oh i realised this might be your formatter so feel free to change it or not :rofl:

2024-03-15 00:56 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/test_hw.hpp
> +        // create our IMU instance
Comments should start with a capital unless they were part of a sentence / paragraph from the previous line

2024-03-15 00:56 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/test_hw.hpp
> +            if (acc_x_conv == 0xFF) {  // ?? idk what a good failure condition is
Maybe put a TODO here, knowing when any of the IMU reads fail is useful for comms

2024-03-15 00:56 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/test_hw.hpp
> +            // HAL_Delay(1);
Commented code

2024-03-15 00:56 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/test_hw.hpp
> +        // inst_packet[7] = calculate_checksum(&inst_packet[2], 5);
scar tissue?

2024-03-15 00:56 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/test_hw.hpp
> +        // while (!packetiser.decode(port.read()));
commented code

2024-03-26 01:23 UTC, dex-k commented
> Initial review. Deleting the .mxproject (or any of the .cproject files, etc) caused a lot of problems when trying to get cube to compile the binaries. What was the reason for deleting these files? I'd rather have them in the repo so when I git clone anytime for any reason I can just start developing and building stuff right away

Can you connfirm that the .mxproject was needed? My testing for #5 didn't show that, but the .project and .cproject were needed. I changed that in the other PR but must have forgotten here

2024-03-26 01:25 UTC, dex-k commented on NUsenseCpp/Core/Src/test_hw.hpp
> +// #include "uart/RS485.h"
All of the stuff in `test_hw.hpp` is kinda all over the shop, probs needs @Claegtun's advice on what to keep or not, it's really just a shittily patched together debugging thing

2024-03-26 01:50 UTC, dex-k commented on NUsenseCpp/Core/Src/test_hw.hpp
> +            if (acc_x_conv == 0xFF) {  // ?? idk what a good failure condition is
This was actually just hanging from some testing - doesn't actually show when reads failed. Removing

2024-03-26 03:08 UTC, dex-k commented on NUsenseCpp/Core/Src/imu.cpp
>      HAL_Delay(1);
I didn't write it, but I assume the delay is needed between setting and reseting the `PWR_MGMT_1_DEVICE_RESET` flag

2024-03-26 03:21 UTC, dex-k commented on NUsenseCpp/Core/Src/test_hw.hpp
> +            // HAL_Delay(1);
Removing all other tests from main in this PR. Updated tests can be added back to main in later PRs (yours and claytons). This way we don't keep unnecessary junk.

2024-03-26 03:21 UTC, dex-k commented on NUsenseCpp/Core/Src/test_hw.hpp
> +        // inst_packet[7] = calculate_checksum(&inst_packet[2], 5);
Removing all other tests from main in this PR. Updated tests can be added back to main in later PRs (yours and claytons). This way we don't keep unnecessary junk.

2024-03-26 03:21 UTC, dex-k commented on NUsenseCpp/Core/Src/test_hw.hpp
> +            link.transmit_poll((uint8_t*) &c, 1, HAL_MAX_DELAY);
Removing all other tests from main in this PR. Updated tests can be added back to main in later PRs (yours and claytons). This way we don't keep unnecessary junk.

2024-03-26 03:28 UTC, dex-k commented on NUsenseCpp/Core/Src/main.cpp
>  }
Agreed, but can probs do later

2024-03-26 03:35 UTC, dex-k commented on NUsenseCpp/Core/Src/imu.cpp
> +using namespace NUsense;
Why's this?

2024-03-26 04:00 UTC, TrentHouliston commented on NUsenseCpp/Core/Src/imu.cpp
> +using namespace NUsense;
You should not ever under almost any circumstance use a using namespace

2024-03-28 00:51 UTC, dex-k commented on NUsenseCpp/Core/Src/imu.cpp
> +using namespace NUsense;
copy that

2024-03-29 22:27 UTC, Claegtun requested changes

2024-03-29 22:27 UTC, Claegtun commented on NUsenseCpp/Core/Inc/settings.h
> +// #define DXL_PWR
```suggestion
// #define FIRST_BUZZ
#define DXL_PWR
```

2024-03-29 22:27 UTC, Claegtun commented on NUsenseCpp/Core/Inc/settings.h
> +// #define TEST_IMU
```suggestion
#define RUN_MAIN
// #define TEST_IMU
```

2024-03-29 22:27 UTC, Claegtun commented on .gitignore
> +.metadata/
```suggestion
.metadata\
.settings
Release\
Debug\
*.launch
```
These are needed, right?

2024-03-30 05:55 UTC, merged