Create the Dynamixel read-write-loop.
NUbots/NUcontroller pull request #7
Opened 2024-03-13 05:02 UTC by Claegtun

This should poll all servos in a loop at around 900 Hz given that the optimisation is set to `-Os` along with `-ffast-math -flto`. 

The whole NUsense operation is wrapped in a class called `NUsenseIO`; a better name is welcome.

Furthermore, the USB receiving code was merged in to test the downstream operation of passing `ServoTarget`s from `ScripTuner` to the actual servos themselves and to get the robot to actually move.

2024-03-14 03:28 UTC, Claegtun commented
May change the flow of servos to be arbitrary rather than dynamic. It will make incorporating and timing the USB transmission easier.

2024-03-14 23:43 UTC, JohanneMontano commented on NUsenseCpp/Core/Inc/signal.h
> +#define RESET_SIGNAL_5() ;
Are we able to make just 1 function which takes a pointer to the port and the pin instead of #defines?

2024-03-15 00:15 UTC, Claegtun commented on NUsenseCpp/Core/Inc/signal.h
> +#define RESET_SIGNAL_5() ;
Maybe. But it is not really that necessary since this is only for debugging. Also, I wanted the functions to be as short as possible without any switch-statement, etc. Passing the port and pin may also make the function more verbose in code.

2024-03-15 00:17 UTC, Claegtun commented on NUsenseCpp/Core/Inc/signal.h
> +#define RESET_SIGNAL_5() ;
As in more difficult to read from a glance, e.g.
`SET_SIGNAL(SPARE1_GPIO_Port, SPARE1_Pin)` instead of just `SET_SIGNAL_5()`.

2024-03-15 00:37 UTC, JohanneMontano requested changes
Some changes and comments

2024-03-15 00:37 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/loop.cpp
>      void NUsenseIO::loop() {
It might be better to get rid of each file containing the implementation of each method of the IO class and put them inside one cpp file instead so we have less files to look at.

2024-03-15 00:37 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO.hpp
> +
Just want to make sure, 

The roles of NUsense IO:
1) Catch bytes from NUC and decoding them to servo targets messages
2) Writing servo targets to dynamixel registers
3) Querying IMU and servo states, updating the related cache
4) Encoding a NUSenseData message and sending this to the NUC via usb

Is this correct?

2024-03-15 00:37 UTC, JohanneMontano commented on NUsenseCpp/Core/Inc/signal.h
> +#define RESET_SIGNAL_5() ;
Also can we have some more docs for these pls ty

2024-03-15 00:37 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/send_request.cpp
> +//#include <fmt/format.h>
```suggestion
```
This can go as we wont be using printf or couts anyway

2024-03-15 00:37 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/test_hw.hpp
> +//#include "uart/rs485_c.h"
Address commented includes

2024-03-15 00:37 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/uart/Port.cpp
>          //handle_rx();
Commented code

2024-03-15 00:37 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/usb/PacketHandler.hpp
> + *      Author: Johanne Montano
I didn't create this :rofl:

2024-03-15 00:37 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/usb/PacketHandler.hpp
> +//#include "main.h" // for debugging on GPIO pins
Address commented code

2024-03-15 00:37 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/usb/protobuf/ServoData.pb.h
> +/* Automatically generated nanopb header */
This file is to be replaced by NUSenseData.pb.h, see branch #3 's current commits

2024-03-15 00:37 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/usb/protobuf/ServoData.pb.c
> +/* Automatically generated nanopb constant definitions */
This file is to be replaced by NUSenseData.pb.c, see branch https://github.com/NUbots/NUcontroller/pull/3 's current commits

2024-03-15 00:37 UTC, JohanneMontano commented on NUsenseCpp/Core/Src/utility/support/MicrosecondTimer.hpp
> +     */
Since we know the frequency of the timer, can't we just make the timer count to f * te-6 then raise a flag after a check if its past the current value within a callback instead of a class?

2024-03-15 00:37 UTC, JohanneMontano commented on NUsenseCpp/USB_DEVICE/App/usbd_cdc_if.c
> +//#include "main.h" // for debugging on GPIO pins
commented code

2024-03-15 00:37 UTC, JohanneMontano commented on NUsenseCpp/USB_DEVICE/App/usbd_cdc_if.h
> +};
IMO its fine to create an instance of this here but it might be better to define this as a utility that lives within usb and include it from there, but if its too hard / hacky to do then no worries

2024-03-15 00:41 UTC, Claegtun commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO.hpp
> +
Yes, basically everything for now.

2024-03-15 00:43 UTC, Claegtun commented on NUsenseCpp/USB_DEVICE/App/usbd_cdc_if.h
> +};
I am pretty sure that it has to live there, because it needs to be C because that file is written in C.

2024-03-15 00:44 UTC, Claegtun commented on NUsenseCpp/USB_DEVICE/App/usbd_cdc_if.h
> +};
I think that I tried to have it as a separate utility, but it didn't work.

2024-03-15 00:48 UTC, Claegtun commented on NUsenseCpp/Core/Src/utility/support/MicrosecondTimer.hpp
> +     */
One still has to poll the flag. Either way, one has to poll something, whether it is a flag set in the ISR or an inequality. I did think about setting the timer to generate an interrupt and use that, but it would mean making multiple timers for each instance, which may have needed singletons, etc. This seemed like the easiest without too much hassle since both have to poll continuously in a loop anyway. 

An interesting alternative was to execute the aftermath in the ISR itself as a callback, but that would be against the convention of keeping ISR's short and would need to pass the relevant objects, e.g. current servo, as global variables or something. It would also still need multiple peripheral timers, one for each instance and therefore for one for each port.

2024-03-15 00:50 UTC, Claegtun commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO.hpp
> +
It is just a dumb way to minimise global variables and to structure files like HardwareIO. The name is more or less meaningless.

2024-03-15 00:54 UTC, Claegtun commented on NUsenseCpp/Core/Src/utility/support/MicrosecondTimer.hpp
> +     */
That is unless there is some magical way to set multiple count-thresholds on a timer. There may be, but I haven't looked too much in it. I know that there are a few CCR's for each timer, but maybe not enough for each port.

2024-03-17 00:21 UTC, Claegtun commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO/loop.cpp
>      void NUsenseIO::loop() {
I was under the impression that many short files were better than one long file. Afterall, the file structure under NUsenseIO is taken from the HardwareIO for the OpenCR setup, and I remember that Dex and Ysobel split the methods in different files because HardwareIO.cpp was getting very long.

2024-03-17 00:31 UTC, Claegtun commented on NUsenseCpp/Core/Src/usb/PacketHandler.hpp
> + *      Author: Johanne Montano
It was originally the comms.hpp file that you wrote. So, you did technically. Also, most of the code is yours.

2024-03-17 00:33 UTC, Claegtun commented on NUsenseCpp/Core/Src/uart/Port.cpp
>          //handle_rx();
I will likely clean up Port.cpp once I have a chance to retest that it works.

2024-03-17 00:34 UTC, Claegtun commented on NUsenseCpp/Core/Src/usb/protobuf/ServoData.pb.h
> +/* Automatically generated nanopb header */
Will likely clean this up when we merge all the stuff later.

2024-03-17 00:34 UTC, Claegtun commented on NUsenseCpp/Core/Src/usb/protobuf/ServoData.pb.c
> +/* Automatically generated nanopb constant definitions */
Will likely clean this up when we merge all the stuff later.

2024-03-17 00:42 UTC, Claegtun commented on NUsenseCpp/Core/Src/test_hw.hpp
> +//#include "uart/rs485_c.h"
Fixed, although we need to clean up that whole file since it is really a dumping ground for test code. Originally, I intended it to be test components of the board one by one kind of like a factory-test for new boards. It may be the subject for another PR.

2024-03-17 00:51 UTC, Claegtun commented on NUsenseCpp/USB_DEVICE/App/usbd_cdc_if.c
> +//#include "main.h" // for debugging on GPIO pins
Fixed.

2024-03-17 00:51 UTC, Claegtun commented on NUsenseCpp/Core/Src/usb/PacketHandler.hpp
> +//#include "main.h" // for debugging on GPIO pins
Fixed.

2024-03-17 00:51 UTC, Claegtun commented on NUsenseCpp/Core/Src/usb/PacketHandler.hpp
> + *      Author: Johanne Montano
Fixed anyway. We likely shouldn't have comment-headers for now until we have a unified system as well as licences.

2024-03-17 00:51 UTC, Claegtun commented on NUsenseCpp/Core/Src/platform/NUsense/NUsenseIO.hpp
> +			}),*/
Fixed; kept only one arrangement.

2024-03-17 00:52 UTC, Claegtun commented on NUsenseCpp/Core/Inc/signal.h
> +#define RESET_SIGNAL_5() ;
Added documentation.

2024-03-17 00:58 UTC, Claegtun commented
May fix up Port.cpp when I get the time next week.

2024-03-19 04:46 UTC, JohanneMontano approved these changes
lgtm

2024-03-19 04:52 UTC, merged